version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: jack2ai/jack-internvl:latest
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ipc: host