version: '3.9'
services:
  server:
    build:
        context: .
        dockerfile: Dockerfile
    image: jack2ai/jack-internvl:latest
    ipc: host
    network_mode: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    command: /bin/bash